#-*- coding:utf-8 -*-
from models import *;

iplayers = [ #(`id`,`gold`,`gold_frozen`,`exp`,`in_auction`,`auctioncenter_id`,`max_card`,`count_card`,`name`,`xn_id`)
	Player( id=1,gold=938,gold_frozen=6,exp=100,name='袁昕',xn_id='crossin'),
	Player( id=2,gold=938,gold_frozen=6,exp=100,name='王震',xn_id='zinking'),
	Player( id=3,gold=938,gold_frozen=6,exp=100,name='赵欣',xn_id='hatevol'),
	Player( id=4,gold=938,gold_frozen=6,exp=100,name='杨展鑫',xn_id='etxian'),
	Player( id=5,gold=938,gold_frozen=6,exp=100,name='马雷',xn_id='malei'),
	Player( id=6,gold=938,gold_frozen=6,exp=100,name='谭雪婷',xn_id='tanjie'),
];

icards = [ #(`id`,`card_class`,`auction_type`,`content`,`name`,`description`)
	Card( id=1, card_class=0, auction_type=1, content=1, name='科罗拉多大峡谷', description='位于美国西部亚利桑那州西北部的凯巴布高原上，科罗拉多河穿流其中。'),
	Card( id=2, card_class=0, auction_type=2, content=1, name='科罗拉多大峡谷', description='位于美国西部亚利桑那州西北部的凯巴布高原上，科罗拉多河穿流其中。'),
	Card( id=3, card_class=0, auction_type=3, content=1, name='科罗拉多大峡谷', description='位于美国西部亚利桑那州西北部的凯巴布高原上，科罗拉多河穿流其中。'),
	Card( id=4, card_class=0, auction_type=1, content=2, name='维多利亚瀑布', description='位于非洲赞比西河中游，赞比亚与津巴布韦接壤处，为世界著名瀑布奇观之一。'),
	Card( id=5, card_class=0, auction_type=2, content=2, name='维多利亚瀑布', description='位于非洲赞比西河中游，赞比亚与津巴布韦接壤处，为世界著名瀑布奇观之一。'),
	Card( id=6, card_class=0, auction_type=3, content=2, name='维多利亚瀑布', description='位于非洲赞比西河中游，赞比亚与津巴布韦接壤处，为世界著名瀑布奇观之一。'),
	Card( id=7, card_class=0, auction_type=1, content=3, name='贝加尔湖', description='容量最大，最深的淡水湖，被称为“西伯利亚的蓝眼睛”，是东亚地区不少民族的发源地。'),
	Card( id=8, card_class=0, auction_type=2, content=3, name='贝加尔湖', description='容量最大，最深的淡水湖，被称为“西伯利亚的蓝眼睛”，是东亚地区不少民族的发源地。'),
	Card( id=9, card_class=0, auction_type=3, content=3, name='贝加尔湖', description='容量最大，最深的淡水湖，被称为“西伯利亚的蓝眼睛”，是东亚地区不少民族的发源地。'),
	Card( id=10, card_class=0, auction_type=1, content=4, name='阿拉斯加冰河湾', description='形成于四千年前的小冰河时期，数千年后冰河不断向前推进，并在1750年时达到鼎盛。'),
	Card( id=11, card_class=0, auction_type=2, content=4, name='阿拉斯加冰河湾', description='形成于四千年前的小冰河时期，数千年后冰河不断向前推进，并在1750年时达到鼎盛。'),
	Card( id=12, card_class=0, auction_type=3, content=4, name='阿拉斯加冰河湾', description='形成于四千年前的小冰河时期，数千年后冰河不断向前推进，并在1750年时达到鼎盛。'),
	Card( id=13, card_class=0, auction_type=1, content=5, name='乞力马扎罗山', description='非洲最高的山脉，素有“非洲屋脊”之称，而许多地理学家则喜欢称它为“非洲之王”。'),
	Card( id=14, card_class=0, auction_type=2, content=5, name='乞力马扎罗山', description='非洲最高的山脉，素有“非洲屋脊”之称，而许多地理学家则喜欢称它为“非洲之王”。'),
	Card( id=15, card_class=0, auction_type=3, content=5, name='乞力马扎罗山', description='非洲最高的山脉，素有“非洲屋脊”之称，而许多地理学家则喜欢称它为“非洲之王”。'),
	Card( id=16, card_class=1, auction_type=1, content=6, name='卢浮宫', description='世界上最古老、最大、最著名的博物馆之一，位于法国巴黎市中心的塞纳河北岸。'),
	Card( id=17, card_class=1, auction_type=2, content=6, name='卢浮宫', description='世界上最古老、最大、最著名的博物馆之一，位于法国巴黎市中心的塞纳河北岸。'),
	Card( id=18, card_class=1, auction_type=3, content=6, name='卢浮宫', description='世界上最古老、最大、最著名的博物馆之一，位于法国巴黎市中心的塞纳河北岸。'),
	Card( id=19, card_class=1, auction_type=1, content=7, name='胡夫金字塔', description='埃及现存规模最大的金字塔，被喻为“世界古代七大奇迹”之一。'),
	Card( id=20, card_class=1, auction_type=2, content=7, name='胡夫金字塔', description='埃及现存规模最大的金字塔，被喻为“世界古代七大奇迹”之一。'),
	Card( id=21, card_class=1, auction_type=3, content=7, name='胡夫金字塔', description='埃及现存规模最大的金字塔，被喻为“世界古代七大奇迹”之一。'),
	Card( id=22, card_class=1, auction_type=1, content=8, name='罗马斗兽场', description='古罗马文明的象征。遗址位于意大利首都罗马市中心，可以容纳近九万人数的观众。'),
	Card( id=23, card_class=1, auction_type=2, content=8, name='罗马斗兽场', description='古罗马文明的象征。遗址位于意大利首都罗马市中心，可以容纳近九万人数的观众。'),
	Card( id=24, card_class=1, auction_type=3, content=8, name='罗马斗兽场', description='古罗马文明的象征。遗址位于意大利首都罗马市中心，可以容纳近九万人数的观众。'),
	Card( id=25, card_class=1, auction_type=1, content=9, name='雅典卫城', description='希腊最杰出的古建筑群，也称为雅典的阿克罗波利斯，为宗教政治的中心地。'),
	Card( id=26, card_class=1, auction_type=2, content=9, name='雅典卫城', description='希腊最杰出的古建筑群，也称为雅典的阿克罗波利斯，为宗教政治的中心地。'),
	Card( id=27, card_class=1, auction_type=3, content=9, name='雅典卫城', description='希腊最杰出的古建筑群，也称为雅典的阿克罗波利斯，为宗教政治的中心地。'),
	Card( id=28, card_class=1, auction_type=1, content=10, name='北京故宫', description='又名紫禁城，位于北京市中心，意为过去的皇宫。世界现存最大、最完整的古建筑群。'),
	Card( id=29, card_class=1, auction_type=2, content=10, name='北京故宫', description='又名紫禁城，位于北京市中心，意为过去的皇宫。世界现存最大、最完整的古建筑群。'),
	Card( id=30, card_class=1, auction_type=3, content=10, name='北京故宫', description='又名紫禁城，位于北京市中心，意为过去的皇宫。世界现存最大、最完整的古建筑群。'),
	Card( id=31, card_class=2, auction_type=1, content=11, name='自由女神像', description='坐落于美国纽约州纽约市附近的自由岛，是法国在1876年赠送给美国独立100周年的礼物。'),
	Card( id=32, card_class=2, auction_type=2, content=11, name='自由女神像', description='坐落于美国纽约州纽约市附近的自由岛，是法国在1876年赠送给美国独立100周年的礼物。'),
	Card( id=33, card_class=2, auction_type=3, content=11, name='自由女神像', description='坐落于美国纽约州纽约市附近的自由岛，是法国在1876年赠送给美国独立100周年的礼物。'),
	Card( id=34, card_class=2, auction_type=1, content=12, name='思想者', description='最初罗丹给这尊雕像命名为《诗人》，意在象征着但丁对于地狱中种种罪恶幽灵的思考。'),
	Card( id=35, card_class=2, auction_type=2, content=12, name='思想者', description='最初罗丹给这尊雕像命名为《诗人》，意在象征着但丁对于地狱中种种罪恶幽灵的思考。'),
	Card( id=36, card_class=2, auction_type=3, content=12, name='思想者', description='最初罗丹给这尊雕像命名为《诗人》，意在象征着但丁对于地狱中种种罪恶幽灵的思考。'),
	Card( id=37, card_class=2, auction_type=1, content=13, name='掷铁饼者', description='这尊被誉为“体育运动之神”的雕像，一望而知是表现投掷铁饼的一个典型瞬间动作。'),
	Card( id=38, card_class=2, auction_type=2, content=13, name='掷铁饼者', description='这尊被誉为“体育运动之神”的雕像，一望而知是表现投掷铁饼的一个典型瞬间动作。'),
	Card( id=39, card_class=2, auction_type=3, content=13, name='掷铁饼者', description='这尊被誉为“体育运动之神”的雕像，一望而知是表现投掷铁饼的一个典型瞬间动作。'),
	Card( id=40, card_class=2, auction_type=1, content=14, name='大卫', description='西方美术史上最值得夸耀的男性人体雕像之一。是思想解放运动在艺术上得到表达的象征。'),
	Card( id=41, card_class=2, auction_type=2, content=14, name='大卫', description='西方美术史上最值得夸耀的男性人体雕像之一。是思想解放运动在艺术上得到表达的象征。\r\n'),
	Card( id=42, card_class=2, auction_type=3, content=14, name='大卫', description='西方美术史上最值得夸耀的男性人体雕像之一。是思想解放运动在艺术上得到表达的象征。'),
	Card( id=43, card_class=2, auction_type=1, content=15, name='狮身人面像', description='又名“斯芬克斯”，坐落在开罗西南的吉萨金字塔群旁，古埃及文明最有代表性的遗迹。'),
	Card( id=44, card_class=2, auction_type=2, content=15, name='狮身人面像', description='又名“斯芬克斯”，坐落在开罗西南的吉萨金字塔群旁，古埃及文明最有代表性的遗迹。'),
	Card( id=45, card_class=2, auction_type=3, content=15, name='狮身人面像', description='又名“斯芬克斯”，坐落在开罗西南的吉萨金字塔群旁，古埃及文明最有代表性的遗迹。'),
	Card( id=46, card_class=3, auction_type=1, content=16, name='兰亭序', description='王羲之得意之笔，被誉为“天下第一行书”，真迹被唐太宗视为稀世珍品而最终殉葬。'),
	Card( id=47, card_class=3, auction_type=2, content=16, name='兰亭序', description='王羲之得意之笔，被誉为“天下第一行书”，真迹被唐太宗视为稀世珍品而最终殉葬。'),
	Card( id=48, card_class=3, auction_type=3, content=16, name='兰亭序', description='王羲之得意之笔，被誉为“天下第一行书”，真迹被唐太宗视为稀世珍品而最终殉葬。'),
	Card( id=49, card_class=3, auction_type=1, content=17, name='死海古卷', description='在死海附近的山洞中发现的羊皮卷，被验证为是一些用希伯莱文书写的早期基督教的圣经。'),
	Card( id=50, card_class=3, auction_type=2, content=17, name='死海古卷', description='在死海附近的山洞中发现的羊皮卷，被验证为是一些用希伯莱文书写的早期基督教的圣经。'),
	Card( id=51, card_class=3, auction_type=3, content=17, name='死海古卷', description='在死海附近的山洞中发现的羊皮卷，被验证为是一些用希伯莱文书写的早期基督教的圣经。'),
	Card( id=52, card_class=3, auction_type=1, content=18, name='独立宣言', description='北美洲十三个英属殖民地宣告自大不列颠王国独立，并宣明此举正当性之文告。'),
	Card( id=53, card_class=3, auction_type=2, content=18, name='独立宣言', description='北美洲十三个英属殖民地宣告自大不列颠王国独立，并宣明此举正当性之文告。'),
	Card( id=54, card_class=3, auction_type=3, content=18, name='独立宣言', description='北美洲十三个英属殖民地宣告自大不列颠王国独立，并宣明此举正当性之文告。'),
	Card( id=55, card_class=3, auction_type=1, content=19, name='汉谟拉比法典', description='目前所知的世界上第一部比较完整的成文法典，汉谟拉比为了向神明显示自己的功绩而纂集。'),
	Card( id=56, card_class=3, auction_type=2, content=19, name='汉谟拉比法典', description='目前所知的世界上第一部比较完整的成文法典，汉谟拉比为了向神明显示自己的功绩而纂集。'),
	Card( id=57, card_class=3, auction_type=3, content=19, name='汉谟拉比法典', description='目前所知的世界上第一部比较完整的成文法典，汉谟拉比为了向神明显示自己的功绩而纂集。'),
	Card( id=58, card_class=3, auction_type=1, content=20, name='罗塞塔石碑', description='石碑上用希腊文字、古埃及文字和当时的通俗体文字刻了埃及国王托勒密五世诏书。'),
	Card( id=59, card_class=3, auction_type=2, content=20, name='罗塞塔石碑', description='石碑上用希腊文字、古埃及文字和当时的通俗体文字刻了埃及国王托勒密五世诏书。'),
	Card( id=60, card_class=3, auction_type=3, content=20, name='罗塞塔石碑', description='石碑上用希腊文字、古埃及文字和当时的通俗体文字刻了埃及国王托勒密五世诏书。'),
	Card( id=61, card_class=4, auction_type=1, content=21, name='牛顿', description='发明了微积分，发现了万有引力定律和经典力学，设计并实际制造了第一架反射式望远镜。'),
	Card( id=62, card_class=4, auction_type=2, content=21, name='牛顿', description='发明了微积分，发现了万有引力定律和经典力学，设计并实际制造了第一架反射式望远镜。'),
	Card( id=63, card_class=4, auction_type=3, content=21, name='牛顿', description='发明了微积分，发现了万有引力定律和经典力学，设计并实际制造了第一架反射式望远镜。'),
	Card( id=64, card_class=4, auction_type=1, content=22, name='孔子', description='编撰了我国第一部编年体史书《春秋》，其言行思想主要载于语录体散文集《论语》。'),
	Card( id=65, card_class=4, auction_type=2, content=22, name='孔子', description='编撰了我国第一部编年体史书《春秋》，其言行思想主要载于语录体散文集《论语》。'),
	Card( id=66, card_class=4, auction_type=3, content=22, name='孔子', description='编撰了我国第一部编年体史书《春秋》，其言行思想主要载于语录体散文集《论语》。'),
	Card( id=67, card_class=4, auction_type=1, content=23, name='爱因斯坦', description='现代物理学的开创者和奠基人，相对论的提出者，“决定论量子力学诠释”的捍卫者。'),
	Card( id=68, card_class=4, auction_type=2, content=23, name='爱因斯坦', description='现代物理学的开创者和奠基人，相对论的提出者，“决定论量子力学诠释”的捍卫者。'),
	Card( id=69, card_class=4, auction_type=3, content=23, name='爱因斯坦', description='现代物理学的开创者和奠基人，相对论的提出者，“决定论量子力学诠释”的捍卫者。'),
	Card( id=70, card_class=4, auction_type=1, content=24, name='君士坦丁大帝', description='世界历史上第一位信仰基督教的皇帝，承认基督教为合法且自由的宗教。'),
	Card( id=71, card_class=4, auction_type=2, content=24, name='君士坦丁大帝', description='世界历史上第一位信仰基督教的皇帝，承认基督教为合法且自由的宗教。'),
	Card( id=72, card_class=4, auction_type=3, content=24, name='君士坦丁大帝', description='世界历史上第一位信仰基督教的皇帝，承认基督教为合法且自由的宗教。'),
	Card( id=73, card_class=4, auction_type=1, content=25, name='达尔文', description='出版了《物种起源》这一划时代的著作，提出了生物进化论学说。'),
	Card( id=74, card_class=4, auction_type=2, content=25, name='达尔文', description='出版了《物种起源》这一划时代的著作，提出了生物进化论学说。'),
	Card( id=75, card_class=4, auction_type=3, content=25, name='达尔文', description='出版了《物种起源》这一划时代的著作，提出了生物进化论学说。'),
	Card( id=76, card_class=5, auction_type=1, content=26, name='伊苏斯之战', description='亚历山大大帝与波斯帝国末代国王大流士三世在伊苏斯进行的一场大战。'),
	Card( id=77, card_class=5, auction_type=2, content=26, name='伊苏斯之战', description='亚历山大大帝与波斯帝国末代国王大流士三世在伊苏斯进行的一场大战。'),
	Card( id=78, card_class=5, auction_type=3, content=26, name='伊苏斯之战', description='亚历山大大帝与波斯帝国末代国王大流士三世在伊苏斯进行的一场大战。'),
	Card( id=79, card_class=5, auction_type=1, content=27, name='特洛伊战争', description='以阿伽门农及阿喀琉斯为首的希腊军进攻以帕里斯及赫克托尔为首的特洛伊城的十年攻城战。'),
	Card( id=80, card_class=5, auction_type=2, content=27, name='特洛伊战争', description='以阿伽门农及阿喀琉斯为首的希腊军进攻以帕里斯及赫克托尔为首的特洛伊城的十年攻城战。'),
	Card( id=81, card_class=5, auction_type=3, content=27, name='特洛伊战争', description='以阿伽门农及阿喀琉斯为首的希腊军进攻以帕里斯及赫克托尔为首的特洛伊城的十年攻城战。'),
	Card( id=82, card_class=5, auction_type=1, content=28, name='滑铁卢战役', description='拿破仑一世的最后一战，这次战役结束了拿破仑帝国。后世用来形容惨败。'),
	Card( id=83, card_class=5, auction_type=2, content=28, name='滑铁卢战役', description='拿破仑一世的最后一战，这次战役结束了拿破仑帝国。后世用来形容惨败。'),
	Card( id=84, card_class=5, auction_type=3, content=28, name='滑铁卢战役', description='拿破仑一世的最后一战，这次战役结束了拿破仑帝国。后世用来形容惨败。'),
	Card( id=85, card_class=5, auction_type=1, content=29, name='诺曼底登陆', description='迄今世界上最大的一次海上登陆作战，接近三百万士兵渡过英吉利海峡前往法国诺曼底。'),
	Card( id=86, card_class=5, auction_type=2, content=29, name='诺曼底登陆', description='迄今世界上最大的一次海上登陆作战，接近三百万士兵渡过英吉利海峡前往法国诺曼底。'),
	Card( id=87, card_class=5, auction_type=3, content=29, name='诺曼底登陆', description='迄今世界上最大的一次海上登陆作战，接近三百万士兵渡过英吉利海峡前往法国诺曼底。'),
	Card( id=88, card_class=5, auction_type=1, content=30, name='淝水之战', description='东晋在淝水以八万军力大胜八十余万前秦军，是我国历史上著名的以弱胜强的战例。'),
	Card( id=89, card_class=5, auction_type=2, content=30, name='淝水之战', description='东晋在淝水以八万军力大胜八十余万前秦军，是我国历史上著名的以弱胜强的战例。'),
	Card( id=90, card_class=5, auction_type=3, content=30, name='淝水之战', description='东晋在淝水以八万军力大胜八十余万前秦军，是我国历史上著名的以弱胜强的战例。'),
	Card( id=91, card_class=6, auction_type=1, content=31, name='阿斯匹林', description='阿斯匹林从发明至今已有百年的历史，人们不断地发现它的新效用，称其为“神奇药”。'),
	Card( id=92, card_class=6, auction_type=2, content=31, name='阿斯匹林', description='阿斯匹林从发明至今已有百年的历史，人们不断地发现它的新效用，称其为“神奇药”。'),
	Card( id=93, card_class=6, auction_type=3, content=31, name='阿斯匹林', description='阿斯匹林从发明至今已有百年的历史，人们不断地发现它的新效用，称其为“神奇药”。'),
	Card( id=94, card_class=6, auction_type=1, content=32, name='轮子', description='被视做人类最古老、最重要的发明，是交通运输的一大突破，更是人类技术的一项重要成就。'),
	Card( id=95, card_class=6, auction_type=2, content=32, name='轮子', description='被视做人类最古老、最重要的发明，是交通运输的一大突破，更是人类技术的一项重要成就。'),
	Card( id=96, card_class=6, auction_type=3, content=32, name='轮子', description='被视做人类最古老、最重要的发明，是交通运输的一大突破，更是人类技术的一项重要成就。'),
	Card( id=97, card_class=6, auction_type=1, content=33, name='斐波那契数列', description='1、1、2、3、5、8……随着数列项数的增加，前一项与后一项之比越来越逼近黄金分割。'),
	Card( id=98, card_class=6, auction_type=2, content=33, name='斐波那契数列', description='1、1、2、3、5、8……随着数列项数的增加，前一项与后一项之比越来越逼近黄金分割。'),
	Card( id=99, card_class=6, auction_type=3, content=33, name='斐波那契数列', description='1、1、2、3、5、8……随着数列项数的增加，前一项与后一项之比越来越逼近黄金分割。'),
	Card( id=100, card_class=6, auction_type=1, content=34, name='细胞学说', description='一切生物都由细胞组成。论证了整个生物界在结构上的统一性，以及在进化上的共同起源。'),
	Card( id=101, card_class=6, auction_type=2, content=34, name='细胞学说', description='一切生物都由细胞组成。论证了整个生物界在结构上的统一性，以及在进化上的共同起源。'),
	Card( id=102, card_class=6, auction_type=3, content=34, name='细胞学说', description='一切生物都由细胞组成。论证了整个生物界在结构上的统一性，以及在进化上的共同起源。'),
	Card( id=103, card_class=6, auction_type=1, content=35, name='阿基米德定律', description='浸在液体（或气体）里的物体受到向上的浮力作用，浮力大小等于被该物体排开液体的重力。'),
	Card( id=104, card_class=6, auction_type=2, content=35, name='阿基米德定律', description='浸在液体（或气体）里的物体受到向上的浮力作用，浮力大小等于被该物体排开液体的重力。'),
	Card( id=105, card_class=6, auction_type=3, content=35, name='阿基米德定律', description='浸在液体（或气体）里的物体受到向上的浮力作用，浮力大小等于被该物体排开液体的重力。'),
	Card( id=106, card_class=7, auction_type=1, content=36, name='最后的晚餐', description='世界美术宝库中最完美的典范杰作。由达·芬奇直接画在米兰一座修道院的餐厅墙上。'),
	Card( id=107, card_class=7, auction_type=2, content=36, name='最后的晚餐', description='世界美术宝库中最完美的典范杰作。由达·芬奇直接画在米兰一座修道院的餐厅墙上。'),
	Card( id=108, card_class=7, auction_type=3, content=36, name='最后的晚餐', description='世界美术宝库中最完美的典范杰作。由达·芬奇直接画在米兰一座修道院的餐厅墙上。'),
	Card( id=109, card_class=7, auction_type=1, content=37, name='自由引导人民', description='取材于1830年法国的七月革命事件，是德拉克罗瓦最具有浪漫主义色彩的作品之一。'),
	Card( id=110, card_class=7, auction_type=2, content=37, name='自由引导人民', description='取材于1830年法国的七月革命事件，是德拉克罗瓦最具有浪漫主义色彩的作品之一。'),
	Card( id=111, card_class=7, auction_type=3, content=37, name='自由引导人民', description='取材于1830年法国的七月革命事件，是德拉克罗瓦最具有浪漫主义色彩的作品之一。'),
	Card( id=112, card_class=7, auction_type=1, content=38, name='向日葵', description='梵高在阳光明媚灿烂的法国南部所作，粗厚和单纯中却又充满了智慧和灵气。'),
	Card( id=113, card_class=7, auction_type=2, content=38, name='向日葵', description='梵高在阳光明媚灿烂的法国南部所作，粗厚和单纯中却又充满了智慧和灵气。'),
	Card( id=114, card_class=7, auction_type=3, content=38, name='向日葵', description='梵高在阳光明媚灿烂的法国南部所作，粗厚和单纯中却又充满了智慧和灵气。'),
	Card( id=115, card_class=7, auction_type=1, content=39, name='清明上河图', description='中国十大传世名画之一，以精致的工笔记录了北宋汴京郊区和城内汴河两岸的建筑和民生。 '),
	Card( id=116, card_class=7, auction_type=2, content=39, name='清明上河图', description='中国十大传世名画之一，以精致的工笔记录了北宋汴京郊区和城内汴河两岸的建筑和民生。 '),
	Card( id=117, card_class=7, auction_type=3, content=39, name='清明上河图', description='中国十大传世名画之一，以精致的工笔记录了北宋汴京郊区和城内汴河两岸的建筑和民生。 '),
	Card( id=118, card_class=7, auction_type=1, content=40, name='西斯廷圣母', description='拉斐尔“圣母像”中的代表作，它以甜美、悠然的抒情风格而闻名遐迩。'),
	Card( id=119, card_class=7, auction_type=2, content=40, name='西斯廷圣母', description='拉斐尔“圣母像”中的代表作，它以甜美、悠然的抒情风格而闻名遐迩。'),
	Card( id=120, card_class=7, auction_type=3, content=40, name='西斯廷圣母', description='拉斐尔“圣母像”中的代表作，它以甜美、悠然的抒情风格而闻名遐迩。'),
];

iAuctionCenters = [ # (`id`,`max_player`,`count_player`,`phase`,`name`,`description`)
	AuctionCenter( id=1, max_player=10, count_player=0, phase=1, name='苏富比拍卖行', description='苏富比拍卖行的描述，to be continued'),
	AuctionCenter( id=2, max_player=10, count_player=0, phase=1, name='佳士得拍卖行', description='佳士得拍卖行的描述，to be continued'),
	AuctionCenter( id=3, max_player=10, count_player=2, phase=1, name='菲利普拍卖行', description='菲利普拍卖行的描述，to be continued'),
	AuctionCenter( id=4, max_player=10, count_player=1, phase=1, name='纳高拍卖公司', description='纳高拍卖公司的描述，to be continued'),
];

iRepurchasePrices = [ # (`id`,`auctioncenter`,`card_class`,`count`,`price_1`,`price_2`,`price_3`,`price_4`)
	RepurchasePrice( id=1, auctioncenter=AuctionCenter.objects.get(id=1), card_class=0, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=2, auctioncenter=AuctionCenter.objects.get(id=1), card_class=1, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=3, auctioncenter=AuctionCenter.objects.get(id=1), card_class=2, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=4, auctioncenter=AuctionCenter.objects.get(id=1), card_class=3, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=5, auctioncenter=AuctionCenter.objects.get(id=1), card_class=4, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=6, auctioncenter=AuctionCenter.objects.get(id=1), card_class=5, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=7, auctioncenter=AuctionCenter.objects.get(id=1), card_class=6, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=8, auctioncenter=AuctionCenter.objects.get(id=1), card_class=7, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=9, auctioncenter=AuctionCenter.objects.get(id=2), card_class=0, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=10, auctioncenter=AuctionCenter.objects.get(id=2), card_class=1, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=11, auctioncenter=AuctionCenter.objects.get(id=2), card_class=2, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=12, auctioncenter=AuctionCenter.objects.get(id=2), card_class=3, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=13, auctioncenter=AuctionCenter.objects.get(id=2), card_class=4, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=14, auctioncenter=AuctionCenter.objects.get(id=2), card_class=5, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=15, auctioncenter=AuctionCenter.objects.get(id=2), card_class=6, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=16, auctioncenter=AuctionCenter.objects.get(id=2), card_class=7, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=17, auctioncenter=AuctionCenter.objects.get(id=3), card_class=0, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=18, auctioncenter=AuctionCenter.objects.get(id=3), card_class=1, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=19, auctioncenter=AuctionCenter.objects.get(id=3), card_class=2, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=20, auctioncenter=AuctionCenter.objects.get(id=3), card_class=3, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=21, auctioncenter=AuctionCenter.objects.get(id=3), card_class=4, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=22, auctioncenter=AuctionCenter.objects.get(id=3), card_class=5, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=23, auctioncenter=AuctionCenter.objects.get(id=3), card_class=6, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=24, auctioncenter=AuctionCenter.objects.get(id=3), card_class=7, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=25, auctioncenter=AuctionCenter.objects.get(id=4), card_class=0, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=26, auctioncenter=AuctionCenter.objects.get(id=4), card_class=1, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=27, auctioncenter=AuctionCenter.objects.get(id=4), card_class=2, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=28, auctioncenter=AuctionCenter.objects.get(id=4), card_class=3, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=29, auctioncenter=AuctionCenter.objects.get(id=4), card_class=4, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=30, auctioncenter=AuctionCenter.objects.get(id=4), card_class=5, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=31, auctioncenter=AuctionCenter.objects.get(id=4), card_class=6, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	RepurchasePrice( id=32, auctioncenter=AuctionCenter.objects.get(id=4), card_class=7, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
];