#-*- coding:utf-8 -*-
from models import *;

iplayers = [ #(`id`,`gold`,`gold_frozen`,`exp`,`in_auction`,`auctioncenter_id`,`max_card`,`count_card`,`name`,`xn_id`)
     Player( id=1,gold=938,gold_frozen=6,exp=100,name='袁昕',xn_id='crossin'),
     Player( id=2,gold=938,gold_frozen=6,exp=100,name='王震',xn_id='zinking'),
     Player( id=3,gold=938,gold_frozen=6,exp=100,name='赵欣',xn_id='hatevol'),
     Player( id=4,gold=938,gold_frozen=6,exp=100,name='杨展鑫',xn_id='etxian'),
     Player( id=5,gold=938,gold_frozen=6,exp=100,name='马雷',xn_id='malei'),
     Player( id=6,gold=938,gold_frozen=6,exp=100,name='谭雪婷',xn_id='tanjie'),
];

icards = [ #(`id`,`card_class`,`auction_type`,`content`,`name`,`description`)
     Card( id=1, card_class=0, auction_type=1, content=1, name='中国类藏品1', description='中国类藏品1的描述，to be continued'),
     Card( id=2, card_class=0, auction_type=2, content=1, name='中国类藏品1', description='中国类藏品1的描述，to be continued'),
     Card( id=3, card_class=0, auction_type=3, content=1, name='中国类藏品1', description='中国类藏品1的描述，to be continued'),
     Card( id=4, card_class=0, auction_type=1, content=2, name='中国类藏品2', description='中国类藏品2的描述，to be continued'),
     Card( id=5, card_class=0, auction_type=2, content=2, name='中国类藏品2', description='中国类藏品2的描述，to be continued'),
     Card( id=6, card_class=0, auction_type=3, content=2, name='中国类藏品2', description='中国类藏品2的描述，to be continued'),
     Card( id=7, card_class=0, auction_type=1, content=3, name='中国类藏品3', description='中国类藏品3的描述，to be continued'),
     Card( id=8, card_class=0, auction_type=2, content=3, name='中国类藏品3', description='中国类藏品3的描述，to be continued'),
     Card( id=9, card_class=0, auction_type=3, content=3, name='中国类藏品3', description='中国类藏品3的描述，to be continued'),
     Card( id=10, card_class=1, auction_type=1, content=4, name='古巴比伦类藏品1', description='古巴比伦类藏品1的描述，to be continued'),
     Card( id=11, card_class=1, auction_type=2, content=4, name='古巴比伦类藏品1', description='古巴比伦类藏品1的描述，to be continued'),
     Card( id=12, card_class=1, auction_type=3, content=4, name='古巴比伦类藏品1', description='古巴比伦类藏品1的描述，to be continued'),
     Card( id=13, card_class=1, auction_type=1, content=5, name='古巴比伦类藏品2', description='古巴比伦类藏品2的描述，to be continued'),
     Card( id=14, card_class=1, auction_type=2, content=5, name='古巴比伦类藏品2', description='古巴比伦类藏品2的描述，to be continued'),
     Card( id=15, card_class=1, auction_type=3, content=5, name='古巴比伦类藏品2', description='古巴比伦类藏品2的描述，to be continued'),
     Card( id=16, card_class=1, auction_type=1, content=6, name='古巴比伦类藏品3', description='古巴比伦类藏品3的描述，to be continued'),
     Card( id=17, card_class=1, auction_type=2, content=6, name='古巴比伦类藏品3', description='古巴比伦类藏品3的描述，to be continued'),
     Card( id=18, card_class=1, auction_type=3, content=6, name='古巴比伦类藏品3', description='古巴比伦类藏品3的描述，to be continued'),
     Card( id=19, card_class=2, auction_type=1, content=7, name='古印度类藏品1', description='古印度类藏品1的描述，to be continued'),
     Card( id=20, card_class=2, auction_type=2, content=7, name='古印度类藏品1', description='古印度类藏品1的描述，to be continued'),
     Card( id=21, card_class=2, auction_type=3, content=7, name='古印度类藏品1', description='古印度类藏品1的描述，to be continued'),
     Card( id=22, card_class=2, auction_type=1, content=8, name='古印度类藏品2', description='古印度类藏品2的描述，to be continued'),
     Card( id=23, card_class=2, auction_type=2, content=8, name='古印度类藏品2', description='古印度类藏品2的描述，to be continued'),
     Card( id=24, card_class=2, auction_type=3, content=8, name='古印度类藏品2', description='古印度类藏品2的描述，to be continued'),
     Card( id=25, card_class=2, auction_type=1, content=9, name='古印度类藏品3', description='古印度类藏品3的描述，to be continued'),
     Card( id=26, card_class=2, auction_type=2, content=9, name='古印度类藏品3', description='古印度类藏品3的描述，to be continued'),
     Card( id=27, card_class=2, auction_type=3, content=9, name='古印度类藏品3', description='古印度类藏品3的描述，to be continued'),
     Card( id=28, card_class=3, auction_type=1, content=10, name='古埃及类藏品1', description='古埃及类藏品1的描述，to be continued'),
     Card( id=29, card_class=3, auction_type=2, content=10, name='古埃及类藏品1', description='古埃及类藏品1的描述，to be continued'),
     Card( id=30, card_class=3, auction_type=3, content=10, name='古埃及类藏品1', description='古埃及类藏品1的描述，to be continued'),
     Card( id=31, card_class=3, auction_type=1, content=11, name='古埃及类藏品2', description='古埃及类藏品2的描述，to be continued'),
     Card( id=32, card_class=3, auction_type=2, content=11, name='古埃及类藏品2', description='古埃及类藏品2的描述，to be continued'),
     Card( id=33, card_class=3, auction_type=3, content=11, name='古埃及类藏品2', description='古埃及类藏品2的描述，to be continued'),
     Card( id=34, card_class=3, auction_type=1, content=12, name='古埃及类藏品3', description='古埃及类藏品3的描述，to be continued'),
     Card( id=35, card_class=3, auction_type=2, content=12, name='古埃及类藏品3', description='古埃及类藏品3的描述，to be continued'),
     Card( id=36, card_class=3, auction_type=3, content=12, name='古埃及类藏品3', description='古埃及类藏品3的描述，to be continued'),
     Card( id=37, card_class=4, auction_type=1, content=13, name='古希腊类藏品1', description='古希腊类藏品1的描述，to be continued'),
     Card( id=38, card_class=4, auction_type=2, content=13, name='古希腊类藏品1', description='古希腊类藏品1的描述，to be continued'),
     Card( id=39, card_class=4, auction_type=3, content=13, name='古希腊类藏品1', description='古希腊类藏品1的描述，to be continued'),
     Card( id=40, card_class=4, auction_type=1, content=14, name='古希腊类藏品2', description='古希腊类藏品2的描述，to be continued'),
     Card( id=41, card_class=4, auction_type=2, content=14, name='古希腊类藏品2', description='古希腊类藏品2的描述，to be continued'),
     Card( id=42, card_class=4, auction_type=3, content=14, name='古希腊类藏品2', description='古希腊类藏品2的描述，to be continued'),
     Card( id=43, card_class=4, auction_type=1, content=15, name='古希腊类藏品3', description='古希腊类藏品3的描述，to be continued'),
     Card( id=44, card_class=4, auction_type=2, content=15, name='古希腊类藏品3', description='古希腊类藏品3的描述，to be continued'),
     Card( id=45, card_class=4, auction_type=3, content=15, name='古希腊类藏品3', description='古希腊类藏品3的描述，to be continued'),
     Card( id=46, card_class=5, auction_type=1, content=16, name='古罗马类藏品1', description='古罗马类藏品1的描述，to be continued'),
     Card( id=47, card_class=5, auction_type=2, content=16, name='古罗马类藏品1', description='古罗马类藏品1的描述，to be continued'),
     Card( id=48, card_class=5, auction_type=3, content=16, name='古罗马类藏品1', description='古罗马类藏品1的描述，to be continued'),
     Card( id=49, card_class=5, auction_type=1, content=17, name='古罗马类藏品2', description='古罗马类藏品2的描述，to be continued'),
     Card( id=50, card_class=5, auction_type=2, content=17, name='古罗马类藏品2', description='古罗马类藏品2的描述，to be continued'),
     Card( id=51, card_class=5, auction_type=3, content=17, name='古罗马类藏品2', description='古罗马类藏品2的描述，to be continued'),
     Card( id=52, card_class=5, auction_type=1, content=18, name='古罗马类藏品3', description='古罗马类藏品3的描述，to be continued'),
     Card( id=53, card_class=5, auction_type=2, content=18, name='古罗马类藏品3', description='古罗马类藏品3的描述，to be continued'),
     Card( id=54, card_class=5, auction_type=3, content=18, name='古罗马类藏品3', description='古罗马类藏品3的描述，to be continued'),
     Card( id=55, card_class=6, auction_type=1, content=19, name='美洲类藏品1', description='美洲类藏品1的描述，to be continued'),
     Card( id=56, card_class=6, auction_type=2, content=19, name='美洲类藏品1', description='美洲类藏品1的描述，to be continued'),
     Card( id=57, card_class=6, auction_type=3, content=19, name='美洲类藏品1', description='美洲类藏品1的描述，to be continued'),
     Card( id=58, card_class=6, auction_type=1, content=20, name='美洲类藏品2', description='美洲类藏品2的描述，to be continued'),
     Card( id=59, card_class=6, auction_type=2, content=20, name='美洲类藏品2', description='美洲类藏品2的描述，to be continued'),
     Card( id=60, card_class=6, auction_type=3, content=20, name='美洲类藏品2', description='美洲类藏品2的描述，to be continued'),
     Card( id=61, card_class=6, auction_type=1, content=21, name='美洲类藏品3', description='美洲类藏品3的描述，to be continued'),
     Card( id=62, card_class=6, auction_type=2, content=21, name='美洲类藏品3', description='美洲类藏品3的描述，to be continued'),
     Card( id=63, card_class=6, auction_type=3, content=21, name='美洲类藏品3', description='美洲类藏品3的描述，to be continued'),
     Card( id=64, card_class=7, auction_type=1, content=22, name='非洲类藏品1', description='非洲类藏品1的描述，to be continued'),
     Card( id=65, card_class=7, auction_type=2, content=22, name='非洲类藏品1', description='非洲类藏品1的描述，to be continued'),
     Card( id=66, card_class=7, auction_type=3, content=22, name='非洲类藏品1', description='非洲类藏品1的描述，to be continued'),
     Card( id=67, card_class=7, auction_type=1, content=23, name='非洲类藏品2', description='非洲类藏品2的描述，to be continued'),
     Card( id=68, card_class=7, auction_type=2, content=23, name='非洲类藏品2', description='非洲类藏品2的描述，to be continued'),
     Card( id=69, card_class=7, auction_type=3, content=23, name='非洲类藏品2', description='非洲类藏品2的描述，to be continued'),
     Card( id=70, card_class=7, auction_type=1, content=24, name='非洲类藏品3', description='非洲类藏品3的描述，to be continued'),
     Card( id=71, card_class=7, auction_type=2, content=24, name='非洲类藏品3', description='非洲类藏品3的描述，to be continued'),
     Card( id=72, card_class=7, auction_type=3, content=24, name='非洲类藏品3', description='非洲类藏品3的描述，to be continued'),
];

iAuctionCenters = [ # (`id`,`max_player`,`count_player`,`phase`,`name`,`description`)
     AuctionCenter( id=1, max_player=10, count_player=0, phase=1, name='苏富比拍卖行', description='苏富比拍卖行的描述，to be continued'),
     AuctionCenter( id=2, max_player=10, count_player=0, phase=1, name='佳士得拍卖行', description='佳士得拍卖行的描述，to be continued'),
     AuctionCenter( id=3, max_player=10, count_player=2, phase=1, name='菲利普拍卖行', description='菲利普拍卖行的描述，to be continued'),
     AuctionCenter( id=4, max_player=10, count_player=1, phase=1, name='纳高拍卖公司', description='纳高拍卖公司的描述，to be continued'),
];

iRepurchasePrices = [ # (`id`,`auctioncenter`,`card_class`,`count`,`price_1`,`price_2`,`price_3`,`price_4`)
     RepurchasePrice( id=1, auctioncenter=AuctionCenter.objects.get(id=1), card_class=0, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=2, auctioncenter=AuctionCenter.objects.get(id=1), card_class=1, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=3, auctioncenter=AuctionCenter.objects.get(id=1), card_class=2, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=4, auctioncenter=AuctionCenter.objects.get(id=1), card_class=3, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=5, auctioncenter=AuctionCenter.objects.get(id=1), card_class=4, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=6, auctioncenter=AuctionCenter.objects.get(id=1), card_class=5, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=7, auctioncenter=AuctionCenter.objects.get(id=1), card_class=6, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=8, auctioncenter=AuctionCenter.objects.get(id=1), card_class=7, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
     RepurchasePrice( id=9, auctioncenter=AuctionCenter.objects.get(id=2), card_class=0, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=10, auctioncenter=AuctionCenter.objects.get(id=2), card_class=1, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=11, auctioncenter=AuctionCenter.objects.get(id=2), card_class=2, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=12, auctioncenter=AuctionCenter.objects.get(id=2), card_class=3, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=13, auctioncenter=AuctionCenter.objects.get(id=2), card_class=4, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=14, auctioncenter=AuctionCenter.objects.get(id=2), card_class=5, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=15, auctioncenter=AuctionCenter.objects.get(id=2), card_class=6, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=16, auctioncenter=AuctionCenter.objects.get(id=2), card_class=7, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
     RepurchasePrice( id=17, auctioncenter=AuctionCenter.objects.get(id=3), card_class=0, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=18, auctioncenter=AuctionCenter.objects.get(id=3), card_class=1, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=19, auctioncenter=AuctionCenter.objects.get(id=3), card_class=2, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=20, auctioncenter=AuctionCenter.objects.get(id=3), card_class=3, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=21, auctioncenter=AuctionCenter.objects.get(id=3), card_class=4, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=22, auctioncenter=AuctionCenter.objects.get(id=3), card_class=5, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=23, auctioncenter=AuctionCenter.objects.get(id=3), card_class=6, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=24, auctioncenter=AuctionCenter.objects.get(id=3), card_class=7, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
     RepurchasePrice( id=25, auctioncenter=AuctionCenter.objects.get(id=4), card_class=0, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=26, auctioncenter=AuctionCenter.objects.get(id=4), card_class=1, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=27, auctioncenter=AuctionCenter.objects.get(id=4), card_class=2, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=28, auctioncenter=AuctionCenter.objects.get(id=4), card_class=3, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=29, auctioncenter=AuctionCenter.objects.get(id=4), card_class=4, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=30, auctioncenter=AuctionCenter.objects.get(id=4), card_class=5, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=31, auctioncenter=AuctionCenter.objects.get(id=4), card_class=6, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
	 RepurchasePrice( id=32, auctioncenter=AuctionCenter.objects.get(id=4), card_class=7, count=0, price_1=0, price_2=0, price_3=0, price_4=0),
];